### ISSUE TITLE
Some Music Cues Don't Play

### ISSUE THREAD

**Issue by OpenRift412** [SamVanheer/halflife-unified-sdk#239]
For whatever reason, music cues at the beginning of Inbound and Unforeseen Consequences don't seem to play at all. The music cue for putting on the HEV Suit _does_ seem to work however, so perhaps it only has an effect on music cued to load at the beginning of a level?

Dependencies:
- [x] #340
- [x] #341
- [x] #342

**Comment by SamVanheer** [comment]
The best solution for this would be to implement a custom mp3 player in the game codebase. I'll need to determine how this is best done, but it'll require ripenting either way to change maps from index-based soundtrack selection to name-based selection.

**Comment by OpenRift412** [comment]
> The best solution for this would be to implement a custom mp3 player in the game codebase. I'll need to determine how this is best done, but it'll require ripenting either way to change maps from index-based soundtrack selection to name-based selection.

Hey, so has there been any progress on this?

**Comment by SamVanheer** [comment]
Not yet. When there is progress this issue will be updated.

**Comment by SamVanheer** [comment]
I've implemented a new music system that doesn't stop playback on map change. It also fixes music stopping if it was started with `worldspawn`'s `sounds` keyvalue.

You can try out the latest dev build to see if it works: https://github.com/SamVanheer/halflife-unified-sdk/releases

**Comment by SamVanheer** [comment]
I forgot to update the installer so it didn't apply the required changes to maps to use ambient_generic. I've uploaded a new release that should do this properly.

Make sure to follow the installation instructions: https://github.com/SamVanheer/halflife-unified-sdk/wiki/Installation-instructions

The logo not showing up is because changes made to support the other campaigns changed the data used to display that. #334 is tracking that, i need to rework a couple of things so each campaign properly looks up the title used.

**Comment by OpenRift412** [comment]
> I forgot to update the installer so it didn't apply the required changes to maps to use ambient_generic. I've uploaded a new release that should do this properly.
> 
> Make sure to follow the installation instructions: https://github.com/SamVanheer/halflife-unified-sdk/wiki/Installation-instructions
> 
> The logo not showing up is because changes made to support the other campaigns changed the data used to display that. #334 is tracking that, i need to rework a couple of things so each campaign properly looks up the title used.

Seems to work, but it doesn't seem to show up at all in my steam library, even after restarting Steam.

**Comment by SamVanheer** [comment]
Is there a liblist.gam file in the mod directory? There should be one.

**Comment by OpenRift412** [comment]
> 

There is, yes, but it still doesn't show anything in the library.

**Comment by SamVanheer** [comment]
You're sure the mod directory is in `Half-Life` and is called `hlu`? It should be showing up in that case.

**Comment by SamVanheer** [comment]
I don't know what could be causing the problem. Steam finds mods by searching for directories in the `Half-Life` directory that contain a `liblist.gam` file. I tested the latest dev build and it found it just fine.

Try reinstalling the mod, if that doesn't work restart Steam.

If that doesn't work either download the Steam installer and install it again on top of the existing installation. It'll refresh the installation.

If that doesn't work either then i don't know what could be causing the problem.

**Comment by SamVanheer** [comment]
Closing since the feature has been fully implemented. If you still have issues getting mods to show up in Steam then please create another issue for that problem.
